version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5  # Don't overwhelm with PRs
    commit-message:
      prefix: "deps"          # Prefix for commit messages
    groups:
      go-dependencies:
        patterns:
          - "*"
